/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router and may be overwritten during npm run dev/build.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PanIndiaRouteImport } from './routes/pan-india'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChilliPowderRouteImport } from './routes/chilli-powder'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const ProductsRoute = ProductsRouteImport.update({ id: '/products', path: '/products', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const PanIndiaRoute = PanIndiaRouteImport.update({ id: '/pan-india', path: '/pan-india', getParentRoute: () => rootRouteImport } as any)
const EnterpriseRoute = EnterpriseRouteImport.update({ id: '/enterprise', path: '/enterprise', getParentRoute: () => rootRouteImport } as any)
const ContactRoute = ContactRouteImport.update({ id: '/contact', path: '/contact', getParentRoute: () => rootRouteImport } as any)
const ChilliPowderRoute = ChilliPowderRouteImport.update({ id: '/chilli-powder', path: '/chilli-powder', getParentRoute: () => rootRouteImport } as any)
const B2bRoute = B2bRouteImport.update({ id: '/b2b', path: '/b2b', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const AboutRoute = AboutRouteImport.update({ id: '/about', path: '/about', getParentRoute: () => rootRouteImport } as any)
const AccountRoute = AccountRouteImport.update({ id: '/account', path: '/account', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({ id: '/$slug', path: '/$slug', getParentRoute: () => ProductsRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/b2b': typeof B2bRoute
  '/chilli-powder': typeof ChilliPowderRoute
  '/contact': typeof ContactRoute
  '/enterprise': typeof EnterpriseRoute
  '/pan-india': typeof PanIndiaRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/b2b': typeof B2bRoute
  '/chilli-powder': typeof ChilliPowderRoute
  '/contact': typeof ContactRoute
  '/enterprise': typeof EnterpriseRoute
  '/pan-india': typeof PanIndiaRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/about' | '/admin' | '/b2b' | '/chilli-powder' | '/contact' | '/enterprise' | '/pan-india' | '/privacy' | '/products' | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/about' | '/admin' | '/b2b' | '/chilli-powder' | '/contact' | '/enterprise' | '/pan-india' | '/privacy' | '/products' | '/products/$slug'
  id: '__root__' | '/' | '/account' | '/about' | '/admin' | '/b2b' | '/chilli-powder' | '/contact' | '/enterprise' | '/pan-india' | '/privacy' | '/products' | '/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  B2bRoute: typeof B2bRoute
  ChilliPowderRoute: typeof ChilliPowderRoute
  ContactRoute: typeof ContactRoute
  EnterpriseRoute: typeof EnterpriseRoute
  PanIndiaRoute: typeof PanIndiaRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': { id: '/products'; path: '/products'; fullPath: '/products'; preLoaderRoute: typeof ProductsRouteImport; parentRoute: typeof rootRouteImport }
    '/privacy': { id: '/privacy'; path: '/privacy'; fullPath: '/privacy'; preLoaderRoute: typeof PrivacyRouteImport; parentRoute: typeof rootRouteImport }
    '/pan-india': { id: '/pan-india'; path: '/pan-india'; fullPath: '/pan-india'; preLoaderRoute: typeof PanIndiaRouteImport; parentRoute: typeof rootRouteImport }
    '/enterprise': { id: '/enterprise'; path: '/enterprise'; fullPath: '/enterprise'; preLoaderRoute: typeof EnterpriseRouteImport; parentRoute: typeof rootRouteImport }
    '/contact': { id: '/contact'; path: '/contact'; fullPath: '/contact'; preLoaderRoute: typeof ContactRouteImport; parentRoute: typeof rootRouteImport }
    '/chilli-powder': { id: '/chilli-powder'; path: '/chilli-powder'; fullPath: '/chilli-powder'; preLoaderRoute: typeof ChilliPowderRouteImport; parentRoute: typeof rootRouteImport }
    '/b2b': { id: '/b2b'; path: '/b2b'; fullPath: '/b2b'; preLoaderRoute: typeof B2bRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/about': { id: '/about'; path: '/about'; fullPath: '/about'; preLoaderRoute: typeof AboutRouteImport; parentRoute: typeof rootRouteImport }
    '/account': { id: '/account'; path: '/account'; fullPath: '/account'; preLoaderRoute: typeof AccountRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/products/$slug': { id: '/products/$slug'; path: '/$slug'; fullPath: '/products/$slug'; preLoaderRoute: typeof ProductsSlugRouteImport; parentRoute: typeof ProductsRoute }
  }
}

interface ProductsRouteChildren { ProductsSlugRoute: typeof ProductsSlugRoute }
const ProductsRouteChildren: ProductsRouteChildren = { ProductsSlugRoute }
const ProductsRouteWithChildren = ProductsRoute._addFileChildren(ProductsRouteChildren)
const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AboutRoute,
  AccountRoute,
  AdminRoute,
  B2bRoute,
  ChilliPowderRoute,
  ContactRoute,
  EnterpriseRoute,
  PanIndiaRoute,
  PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
